name: learner-bruh-lms
services:
- name: web
  github:
    repo: dpgaus09/CreatorOS
    branch: main
  build_command: chmod +x .do/deploy.sh && ./.do/deploy.sh
  run_command: npm run start
  envs:
  - key: DATABASE_URL
    scope: RUN_TIME
    value: ${db.DATABASE_URL}
  - key: NODE_ENV
    scope: RUN_TIME
    value: production
  - key: PORT
    scope: RUN_TIME
    value: "8080"
  - key: HOST
    scope: RUN_TIME
    value: "0.0.0.0"
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xs
  health_check:
    http_path: /api/health
    initial_delay_seconds: 30
    period_seconds: 10
    timeout_seconds: 5
    success_threshold: 1
    failure_threshold: 3
  
databases:
- name: db
  engine: PG
  version: "14"